#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : s2tc
Version  : f6ec862d7594e29ae80a6e49f66ad4c76cf09abc
Release  : 5
URL      : https://github.com/divVerent/s2tc/archive/f6ec862d7594e29ae80a6e49f66ad4c76cf09abc.tar.gz
Source0  : https://github.com/divVerent/s2tc/archive/f6ec862d7594e29ae80a6e49f66ad4c76cf09abc.tar.gz
Summary  : Library for S2TC texture compression
Group    : Development/Tools
License  : MIT
Requires: s2tc-bin
Requires: s2tc-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : mesa-dev

%description
S2TC Environment Variables
==========================
Color Distance Function
-----------------------
The following color distance functions can be selected by setting the
environment variable `S2TC_COLORDIST_MODE`:

%package bin
Summary: bin components for the s2tc package.
Group: Binaries

%description bin
bin components for the s2tc package.


%package dev
Summary: dev components for the s2tc package.
Group: Development
Requires: s2tc-bin
Provides: s2tc-devel

%description dev
dev components for the s2tc package.


%package dev32
Summary: dev32 components for the s2tc package.
Group: Default
Requires: s2tc-bin
Requires: s2tc-dev

%description dev32
dev32 components for the s2tc package.


%package doc
Summary: doc components for the s2tc package.
Group: Documentation

%description doc
doc components for the s2tc package.


%prep
%setup -q -n s2tc-f6ec862d7594e29ae80a6e49f66ad4c76cf09abc
pushd ..
cp -a s2tc-f6ec862d7594e29ae80a6e49f66ad4c76cf09abc build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1483889210
%autogen --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%autogen --disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/s2tc_compress
%exclude /usr/bin/s2tc_decompress
%exclude /usr/bin/s2tc_from_s3tc

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/txc_dxtn.h
%exclude /usr/lib64/pkgconfig/txc_dxtn.pc
/usr/lib64/libtxc_dxtn.so

%files dev32
%defattr(-,root,root,-)
%exclude /usr/lib32/pkgconfig/32txc_dxtn.pc
%exclude /usr/lib32/pkgconfig/txc_dxtn.pc
/usr/lib32/libtxc_dxtn.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
